
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class AnaEkran extends javax.swing.JFrame {

    public AnaEkran() {
        initComponents();
        
    
        MusteriListele ml = new MusteriListele();
        tblMusteri.setModel(ml.listeleme());
        SiparisGetir sg = new SiparisGetir();
        tblSiparisler.setModel(sg.siparisListele());

        chooserStart.setDateFormatString("yyyy/MM/dd");
        Date date = new Date();
        chooserStart.setDate(date);

        chooserEnd.setDateFormatString("yyyy/MM/dd");
        chooserEnd.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSiparisler = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtAdi = new javax.swing.JTextField();
        txtSoyadi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonSeciliSil = new javax.swing.JButton();
        buttonTumunuSil = new javax.swing.JButton();
        buttonGununSiparisleri = new javax.swing.JButton();
        buttonYedek = new javax.swing.JButton();
        chooserStart = new com.toedter.calendar.JDateChooser();
        chooserEnd = new com.toedter.calendar.JDateChooser();
        buttonGetir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusteri = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        buttonYeniMusteri = new javax.swing.JButton();
        buttonMusteriDuzenle = new javax.swing.JButton();
        buttonMusteriSil = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        buttonYenile = new javax.swing.JButton();
        buttonYeniSiparis = new javax.swing.JButton();
        buttonYolaCikti = new javax.swing.JButton();
        buttonTeslimEdildi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Su Satış Otamasyonu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Siparişler"));

        tblSiparisler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSiparisler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSiparislerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSiparisler);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Arama"));

        txtAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdiActionPerformed(evt);
            }
        });
        txtAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdiKeyReleased(evt);
            }
        });

        txtSoyadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoyadiKeyReleased(evt);
            }
        });

        jLabel1.setText("Müşteri Adı");

        jLabel2.setText("Müşteri Soyadı");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tablo İşlemleri"));

        buttonSeciliSil.setText("Seçili Olanı Sil");
        buttonSeciliSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeciliSilActionPerformed(evt);
            }
        });

        buttonTumunuSil.setText("Tümünü Sil");
        buttonTumunuSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTumunuSilActionPerformed(evt);
            }
        });

        buttonGununSiparisleri.setText("Bu Günün Siparişleri");
        buttonGununSiparisleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGununSiparisleriActionPerformed(evt);
            }
        });

        buttonYedek.setText("Yedek Al");
        buttonYedek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYedekActionPerformed(evt);
            }
        });

        buttonGetir.setText("Getir");
        buttonGetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonSeciliSil)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTumunuSil))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonGununSiparisleri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonYedek)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chooserEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(chooserStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonGetir))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSeciliSil)
                        .addComponent(buttonTumunuSil))
                    .addComponent(chooserStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGetir))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonGununSiparisleri)
                            .addComponent(buttonYedek))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooserEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Müşteriler"));

        tblMusteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMusteri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMusteriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMusteri);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        buttonYeniMusteri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/kullanici.png"))); // NOI18N
        buttonYeniMusteri.setText("Yeni Müşteri");
        buttonYeniMusteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYeniMusteriActionPerformed(evt);
            }
        });

        buttonMusteriDuzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/update.png"))); // NOI18N
        buttonMusteriDuzenle.setText("Müşteri Düzenle");
        buttonMusteriDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMusteriDuzenleActionPerformed(evt);
            }
        });

        buttonMusteriSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/delete.png"))); // NOI18N
        buttonMusteriSil.setText("Müşteri Sil");
        buttonMusteriSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMusteriSilMouseClicked(evt);
            }
        });
        buttonMusteriSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMusteriSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(buttonYeniMusteri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMusteriDuzenle)
                .addGap(18, 18, 18)
                .addComponent(buttonMusteriSil, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonYeniMusteri)
                    .addComponent(buttonMusteriDuzenle)
                    .addComponent(buttonMusteriSil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonYenile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Refresh.png"))); // NOI18N
        buttonYenile.setText("Yenile");
        buttonYenile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYenileActionPerformed(evt);
            }
        });

        buttonYeniSiparis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new.png"))); // NOI18N
        buttonYeniSiparis.setText("Yeni Sipariş");
        buttonYeniSiparis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYeniSiparisActionPerformed(evt);
            }
        });

        buttonYolaCikti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/yolda.png"))); // NOI18N
        buttonYolaCikti.setText("Yolda");
        buttonYolaCikti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYolaCiktiActionPerformed(evt);
            }
        });

        buttonTeslimEdildi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/teslim.png"))); // NOI18N
        buttonTeslimEdildi.setText("Teslim");
        buttonTeslimEdildi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTeslimEdildiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(buttonYeniSiparis, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonYolaCikti)
                .addGap(18, 18, 18)
                .addComponent(buttonTeslimEdildi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonYenile)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonYeniSiparis)
                    .addComponent(buttonYolaCikti)
                    .addComponent(buttonTeslimEdildi)
                    .addComponent(buttonYenile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static String id = "";
    private void tblMusteriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMusteriMouseClicked
        id = (String) tblMusteri.getValueAt(tblMusteri.getSelectedRow(), 0);

        // Cift tiklanirsa siparis ekleme alanini ac
        if (evt.getClickCount() == 2) {
            SiparisFrame sf = new SiparisFrame();
            sf.setVisible(true);
        }
    }//GEN-LAST:event_tblMusteriMouseClicked

    public String getir() {
        return id;
    }


    private void buttonMusteriSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMusteriSilActionPerformed

               int confirmed = JOptionPane.showConfirmDialog(this, 
        "Silmek istediğinizden emin misiniz?", "Silme İşlemi",
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
        MusteriSil ms = new MusteriSil();
        ms.sil(id);
        MusteriListele ml = new MusteriListele();
        tblMusteri.setModel(ml.listeleme());

        id = "";
      
    }
        
        


    }//GEN-LAST:event_buttonMusteriSilActionPerformed
    String sid = "";
    private void buttonSeciliSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeciliSilActionPerformed
        
                     int confirmed = JOptionPane.showConfirmDialog(this, 
        "Silmek istediğinizden emin misiniz?", "Silme İşlemi",
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
       SiparisSil ss = new SiparisSil();
        ss.sil(sid);
        SiparisGetir sg = new SiparisGetir();
        tblSiparisler.setModel(sg.siparisListele());
        sid = "";
      
    }
      
        
        
    }//GEN-LAST:event_buttonSeciliSilActionPerformed


    private void tblSiparislerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSiparislerMouseClicked
        sid = "" + tblSiparisler.getValueAt(tblSiparisler.getSelectedRow(), 0);
    }//GEN-LAST:event_tblSiparislerMouseClicked

    private void buttonTumunuSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTumunuSilActionPerformed
      
                     int confirmed = JOptionPane.showConfirmDialog(this, 
        "Silmek istediğinizden emin misiniz?", "Silme İşlemi",
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      String query = "delete from siparisler";
        DB db = new DB();
        try {
            db.baglan().executeUpdate(query);
        } catch (Exception e) {
        } finally {
            db.kapat();
        }

        SiparisGetir sg = new SiparisGetir();
        tblSiparisler.setModel(sg.siparisListele());
      
    }
        
        
        

    }//GEN-LAST:event_buttonTumunuSilActionPerformed

    private void buttonYeniSiparisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYeniSiparisActionPerformed

        if (!id.equals("")) {
            SiparisFrame sf = new SiparisFrame();
        sf.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Lütfen bir müşteri seçiniz!");
        }

    }//GEN-LAST:event_buttonYeniSiparisActionPerformed

    private void buttonYenileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYenileActionPerformed

        SiparisGetir sg = new SiparisGetir();
        tblSiparisler.setModel(sg.siparisListele());

        MusteriListele ml = new MusteriListele();
        tblMusteri.setModel(ml.listeleme());
    }//GEN-LAST:event_buttonYenileActionPerformed

    private void buttonYolaCiktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYolaCiktiActionPerformed

        if (!sid.equals("")) {
            System.out.println("id:" + sid);
            String query = "UPDATE siparisler SET sdurum = 1 WHERE sid = '" + sid + "'";
            DB db = new DB();
            try {
                db.baglan().executeUpdate(query);
            } catch (Exception e) {
            } finally {
                db.kapat();
            }
            SiparisGetir sg = new SiparisGetir();
            tblSiparisler.setModel(sg.siparisListele());
        }
    }//GEN-LAST:event_buttonYolaCiktiActionPerformed

    private void buttonTeslimEdildiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTeslimEdildiActionPerformed

        String query = "update siparisler set sdurum=2 where sid ='" + sid + "'";
        DB db = new DB();
        if (!sid.equals("")) {
            try {
                db.baglan().executeUpdate(query);
            } catch (Exception e) {
            } finally {
                db.kapat();
            }
        }
        SiparisGetir sg = new SiparisGetir();
        tblSiparisler.setModel(sg.siparisListele());
    }//GEN-LAST:event_buttonTeslimEdildiActionPerformed

    private void buttonYeniMusteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYeniMusteriActionPerformed

        MusteriFrame mf = new MusteriFrame();
        mf.setVisible(true);
    }//GEN-LAST:event_buttonYeniMusteriActionPerformed

    private void buttonMusteriDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMusteriDuzenleActionPerformed

        if (!id.equals("")) {
            MusteriDuzenleFrame mdf = new MusteriDuzenleFrame();
            mdf.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen bir satır seçiniz.");
        }

    }//GEN-LAST:event_buttonMusteriDuzenleActionPerformed

    static String aId = "";
    
    private void buttonGununSiparisleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGununSiparisleriActionPerformed

        GununSiparisleri gs = new GununSiparisleri();
        tblSiparisler.setModel(gs.listele());
    }//GEN-LAST:event_buttonGununSiparisleriActionPerformed

    private void buttonYedekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYedekActionPerformed

        
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("choosertitle");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        
        

        String url = "db/sukayit.db";
        Path p1 = Paths.get(url);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : " + chooser.getSelectedFile());

            String url2 = "" + chooser.getSelectedFile() + "/yedek.db";
            Path p2 = Paths.get(url2);
            try {
                Files.copy(p1, p2, REPLACE_EXISTING);       
            } catch (Exception e) {
                System.err.println("Kopyalama hatası: " + e);
            }
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_buttonYedekActionPerformed
    ArrayList<Siparis> alst = new ArrayList<>();
    
    private void buttonGetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetirActionPerformed
        alst.clear();
        String basla = ((JTextField)chooserStart.getDateEditor().getUiComponent()).getText();
        String bitir = ((JTextField)chooserEnd.getDateEditor().getUiComponent()).getText();
        
        DB db = new DB();
        String query = "select * from siparisler where stime between '"+basla+"' and '"+bitir+"' ";
        
        try {
            
            ResultSet rs = db.baglan().executeQuery(query);
            while (rs.next()) {                
                Siparis ks = new Siparis();
                ks.setId(rs.getString("" + MEnum.sid));
                ks.setAdi(rs.getString("" + MEnum.smusteriadi));
                ks.setSoyadi(rs.getString("" + MEnum.smusterisoyadi));
                ks.setDurum(rs.getString(""+MEnum.sdurum));
                ks.setAdres(rs.getString("" + MEnum.sadres));
                ks.setTel(rs.getString("" + MEnum.stelefon));
                ks.setTutar(rs.getString("" + MEnum.stutar));

                alst.add(ks);
                
            }
            
        } catch (Exception e) {
            
            System.err.println("Tarih hata: " + e);
        }finally{
            db.kapat();
        }
        
        DefaultTableModel dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }            
        };
        //sutun bilgisi
        dtm.addColumn("id");
        dtm.addColumn("İsim");
        dtm.addColumn("Soyisim");
        dtm.addColumn("Durum");
        dtm.addColumn("Adres");
        dtm.addColumn("Telefon");
        dtm.addColumn("Tutar");
        String durum="";
        for (Siparis l : alst) {
            if (l.getDurum().equals("0")) {
                durum = "Hazırlanıyor";
            }else if(l.getDurum().equals("1")){
                durum = "Yolda";
            }else if(l.getDurum().equals("2")){
                durum = "Teslim Edildi";
            }
            dtm.addRow(new String[]{l.getId(), l.getAdi(), l.getSoyadi(),durum, l.getAdres(),l.getTel(), l.getTutar()});
            durum = "";

        }
        tblSiparisler.setModel(dtm);
    }//GEN-LAST:event_buttonGetirActionPerformed

    ArrayList<Musteri> mls = new ArrayList<>();
    private void txtAdiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdiKeyReleased
        mls.clear();
        String ad = txtAdi.getText();
        String soyAd = txtSoyadi.getText();

       
            String query = "select * from musteriler where  madi like '"+ad+"%' and msoyadi like '"+soyAd+"%'  ";
            DB db = new DB();

            try {
                ResultSet rs = db.baglan().executeQuery(query);
                
                while (rs.next()) {                    
                    Musteri m = new Musteri();
                    m.setAd(rs.getString(""+MEnum.madi));
                    m.setAdres(rs.getString(""+MEnum.madres));
                    m.setId(rs.getString(""+MEnum.mid));
                    m.setSoyad(rs.getString(""+MEnum.msoyadi));
                    m.setTel(rs.getString(""+MEnum.mtelefon));
                    mls.add(m);
                }
                
            } catch (Exception e) {
                System.err.println("Arama id cekme hatasi: " + e);
            } finally {
                db.kapat();
            }
            
            DefaultTableModel tabel = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        
        tabel.addColumn("id");
        tabel.addColumn("İsim");
        tabel.addColumn("Soyisim");
        tabel.addColumn("Telefon");
        tabel.addColumn("Adres");

        for (Musteri l : mls) {

            tabel.addRow(new String[]{l.getId(), l.getAd(), l.getSoyad(), l.getTel(), l.getAdres()});

        }
        
        tblMusteri.setModel(tabel);
       

    }//GEN-LAST:event_txtAdiKeyReleased

    private void txtSoyadiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoyadiKeyReleased
       mls.clear();
        String ad = txtAdi.getText();
        String soyAd = txtSoyadi.getText();

       
            String query = "select * from musteriler where  madi like '"+ad+"%' and msoyadi like '"+soyAd+"%'  ";
            DB db = new DB();

            try {
                ResultSet rs = db.baglan().executeQuery(query);
                
                while (rs.next()) {                    
                    Musteri m = new Musteri();
                    m.setAd(rs.getString(""+MEnum.madi));
                    m.setAdres(rs.getString(""+MEnum.madres));
                    m.setId(rs.getString(""+MEnum.mid));
                    m.setSoyad(rs.getString(""+MEnum.msoyadi));
                    m.setTel(rs.getString(""+MEnum.mtelefon));
                    mls.add(m);
                }
                
            } catch (Exception e) {
                System.err.println("Arama id cekme hatasi: " + e);
            } finally {
                db.kapat();
            }
            
            DefaultTableModel tabel = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        
        tabel.addColumn("id");
        tabel.addColumn("İsim");
        tabel.addColumn("Soyisim");
        tabel.addColumn("Telefon");
        tabel.addColumn("Adres");

        for (Musteri l : mls) {

            tabel.addRow(new String[]{l.getId(), l.getAd(), l.getSoyad(), l.getTel(), l.getAdres()});

        }
        
        tblMusteri.setModel(tabel);
    }//GEN-LAST:event_txtSoyadiKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirmed = JOptionPane.showConfirmDialog(this, 
        "Çıkmak istediğinizden emin misiniz?", "Exit Program Message Box",
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      dispose();
    }
    }//GEN-LAST:event_formWindowClosing

    private void buttonMusteriSilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMusteriSilMouseClicked
   
    }//GEN-LAST:event_buttonMusteriSilMouseClicked

    private void txtAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdiActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGetir;
    private javax.swing.JButton buttonGununSiparisleri;
    private javax.swing.JButton buttonMusteriDuzenle;
    private javax.swing.JButton buttonMusteriSil;
    private javax.swing.JButton buttonSeciliSil;
    private javax.swing.JButton buttonTeslimEdildi;
    private javax.swing.JButton buttonTumunuSil;
    private javax.swing.JButton buttonYedek;
    private javax.swing.JButton buttonYeniMusteri;
    private javax.swing.JButton buttonYeniSiparis;
    private javax.swing.JButton buttonYenile;
    private javax.swing.JButton buttonYolaCikti;
    private com.toedter.calendar.JDateChooser chooserEnd;
    private com.toedter.calendar.JDateChooser chooserStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tblMusteri;
    public static javax.swing.JTable tblSiparisler;
    private javax.swing.JTextField txtAdi;
    private javax.swing.JTextField txtSoyadi;
    // End of variables declaration//GEN-END:variables
}
